name: DO-progression
dependencies:
    - python=3.5.*
    - numpy=1.13.*
    - scipy=0.19.*
    - pandas=0.21.*
    - matplotlib=2.1.*
    - h5py=2.7.*
    - emcee=2.2.1
    - joblib=0.11.*
    - xarray=0.9.6
